const SMALL_SCREEN_WIDTH = 576;
const MEDIUM_SCREEN_WIDTH = 768;
const LARGE_SCREEN_WIDTH = 992;
const EXTRA_LARGE_SCREEN_WIDTH = 1200;

export {
  SMALL_SCREEN_WIDTH,
  MEDIUM_SCREEN_WIDTH,
  LARGE_SCREEN_WIDTH,
  EXTRA_LARGE_SCREEN_WIDTH
};

